### ISSUE TITLE
Add Content to apiRoutes file

### ISSUE THREAD

**Issue by Nicolejeanne** [HNPR/Wingman#16]
Determine routes and add to existing file

**Comment by YenPingLiu** [comment]
### **Static routes:**

- / (home page)
- /login (login page)
- /auth (authentication routes)

### API routes

- /api/requests (get list of all requests, post single request)
- /api/users (get list of all logged users)

**Comment by Nicolejeanne** [comment]
## Additional API Route
  /api/user/:userid

**Comment by Nicolejeanne** [comment]
api routes functioning
