### ISSUE TITLE
Wingman details

### ISSUE THREAD

**Issue by haleyashtonn** [HNPR/Wingman#55]
# Wingman final details

## LOGIN
1. More space between text and sign in with google

## PROFILE
1. Center and split up buttons, make smaller potentially
1. Delete main, large logo
1. Table color change for heading (both requested walks and volunteered)
1. Add icons for completed/incomplete 
4a. https://semantic-ui.com/elements/icon.html
1. Make profile image larger
1. Spin profile logo
1. On-click to profile
1. Edit user details? (font, size, etc.)

## ABOUT
1. Stack images and descriptions

## REQUEST/VOLUNTEER
1. Modal color change

## ALL PAGES
1. Center copyright
1. Nav
1. Hide selection on-click

### I'll be working in `stylin` for a couple hours tonight! Good luck!

@RaynorFisher @Nicolejeanne @YenPingLiu

**Comment by Nicolejeanne** [comment]
# Wingman final details

## LOGIN
- [x] 1. More space between text and sign in with google


## PROFILE
- [x] 1. Center and split up buttons, make smaller potentially
- [x] 1. Delete main, large logo
- [ ] 1. Table color change for heading (both requested walks and volunteered)
- [x] 1. Add icons for completed/incomplete 
4a. https://semantic-ui.com/elements/icon.html
- [x] 1. Make profile image larger
- [ ] 1. Spin profile logo
- [x] 1. On-click to profile
- [x] 1. Edit user details? (font, size, etc.)

## ABOUT
- [x] 1. Stack images and descriptions

## REQUEST/VOLUNTEER
- [x] 1. Modal color change

## ALL PAGES
- [x] 1. Center copyright
- [x] 1. Nav
- [x] 1. Hide selection on-click

**Comment by Nicolejeanne** [comment]
I think we took care of business tonight. Enough to close this issue!
