### ISSUE TITLE
Establish Heroku Pipelines

### ISSUE THREAD

**Issue by Nicolejeanne** [HNPR/Wingman#6]
Establish Heroku Pipelines

**Comment by YenPingLiu** [comment]
I have added a pipeline to Heroku for to monitor the master branch of this Wingman repo. Once we have some viable code, we should try a merge to master and see if it shows up on the site.

BTW this deployed app is here: https://wingman-hnpr.herokuapp.com/

**Comment by YenPingLiu** [comment]
Google API key for authentication and cookie keys are added

**Comment by Nicolejeanne** [comment]
The only reason I have not marked this as complete is because I think we should wait until we push to master for the first time and verify everything is working as we think it should.

**Comment by Nicolejeanne** [comment]
app is deployed through heroku
