### ISSUE TITLE
User Authentication

### ISSUE THREAD

**Issue by Nicolejeanne** [HNPR/Wingman#8]
Determine what kind of user authentication we will use and how we will implement it

**Comment by Nicolejeanne** [comment]
Suggestions for authentications: JSON Web Tokens, Sessions, Firebase

**Comment by YenPingLiu** [comment]
I started using PassportJS with the Google OAuth strategy to authenticate our users. So far I'm able to get OAuth working thru Google and returning some meaningful IDs and Display Names from Google

**Comment by Nicolejeanne** [comment]
User authentication is working from the demo we saw last night. I'm going to close this issue and add a new issue to grab more data from Google beyond the ID and display names.
